import test from 'node:test';import assert from 'node:assert/strict';import {DatabaseSync} from 'node:sqlite';import {readFileSync,readdirSync} from 'node:fs';
import {claimRun,reserveCall,stopRun,canContinue,finishCall} from '../lib/durable-execution.mts';
function setup(){const sqlite=new DatabaseSync(':memory:');for(const f of readdirSync('drizzle').filter(x=>x.endsWith('.sql')).sort())sqlite.exec(readFileSync('drizzle/'+f,'utf8'));sqlite.prepare("INSERT INTO execution_grants(owner,grant_id,expires_at,status) VALUES ('owner','grant',1000000,'approved')").run();
 const db={prepare(sql){return {bind(...values){const q=sqlite.prepare(sql);return {all:async()=>({results:q.all(...values)}),first:async()=>q.get(...values),run:async()=>q.run(...values),execute(){if(sql.includes('RETURNING'))return {results:q.all(...values)};const r=q.run(...values);return {meta:{changes:r.changes}};}};}};},async batch(statements){sqlite.exec('BEGIN IMMEDIATE');try{const r=statements.map(s=>s.execute());sqlite.exec('COMMIT');return r;}catch(e){sqlite.exec('ROLLBACK');throw e;}}};return {db,sqlite};}
const call=(n,arm='single')=>({owner:'owner',grantId:'grant',runId:'run',callId:'call-'+n,arm,inputBytes:8000,outputTokens:4096});
test('only one concurrent run acquires owner lock',async()=>{const {db}=setup();const r=await Promise.allSettled([claimRun(db,'owner','grant','run',100),claimRun(db,'owner','grant','second',100)]);assert.equal(r.filter(x=>x.status==='fulfilled').length,1);});
test('one atomic reservation across duplicate attempts',async()=>{const {db,sqlite}=setup();await claimRun(db,'owner','grant','run',100);const r=await Promise.allSettled([reserveCall(db,call(1),10000),reserveCall(db,call(1),10000)]);assert.equal(r.filter(x=>x.status==='fulfilled').length,1);assert.equal(sqlite.prepare('SELECT calls_used FROM execution_grants').get().calls_used,1);});
test('each arm capped equally and total remains six',async()=>{const {db,sqlite}=setup();await claimRun(db,'owner','grant','run',100);for(let i=1;i<=3;i++)await reserveCall(db,call(i),i*10000);await assert.rejects(reserveCall(db,call(4),40000));for(let i=4;i<=6;i++)await reserveCall(db,call(i,'multi'),i*10000);await assert.rejects(reserveCall(db,call(7,'multi'),70000));assert.equal(sqlite.prepare('SELECT calls_used FROM execution_grants').get().calls_used,6);});
test('cross owner, wrong run, expiry and rate blocked',async()=>{const {db}=setup();await claimRun(db,'owner','grant','run',100);await assert.rejects(reserveCall(db,{...call(1),owner:'other'},10000));await assert.rejects(reserveCall(db,{...call(1),runId:'other'},10000));await assert.rejects(reserveCall(db,call(1),1000001));await reserveCall(db,call(1),10000);await assert.rejects(reserveCall(db,call(2),10001));});
test('stop survives reconstruction and prevents dispatch',async()=>{const {db}=setup();await claimRun(db,'owner','grant','run',100);await stopRun(db,'owner','grant');assert.equal(await canContinue(db,'owner','grant','run',100),false);await assert.rejects(reserveCall(db,call(1),10000));});
test('failed calls keep budget, result updates are idempotent',async()=>{const {db,sqlite}=setup();await claimRun(db,'owner','grant','run',100);await reserveCall(db,call(1),10000);await finishCall(db,{...call(1),status:'failed',result:{error:'TIMEOUT'}});await finishCall(db,{...call(1),status:'succeeded',result:{text:'late'}});assert.equal(sqlite.prepare('SELECT calls_used FROM execution_grants').get().calls_used,1);assert.equal(sqlite.prepare('SELECT status FROM execution_calls').get().status,'failed');});

test('new user message gets a new bounded grant but same message cannot replay',async()=>{const {db,sqlite}=setup();const {startChatGrant}=await import('../lib/durable-execution.mts');await assert.rejects(startChatGrant(db,'owner','new-trigger',100));await stopRun(db,'owner','grant');await startChatGrant(db,'owner','new-trigger',200);assert.equal(sqlite.prepare('SELECT grant_id FROM execution_grants').get().grant_id,'new-trigger');await assert.rejects(startChatGrant(db,'owner','new-trigger',300));});
test('old consumed user trigger cannot reset after a newer round',async()=>{const {db}=setup();const {startChatGrant}=await import('../lib/durable-execution.mts');await claimRun(db,'owner','grant','run',100);await reserveCall(db,call(1),10000);await stopRun(db,'owner','grant');await startChatGrant(db,'owner','new-trigger',20000);await stopRun(db,'owner','new-trigger');await assert.rejects(startChatGrant(db,'owner','grant',30000));});
test('stopped or superseded results cannot enter chat atomically',async()=>{const {db,sqlite}=setup();const {CHAT_APPEND_SQL}=await import('../lib/durable-execution.mts');await claimRun(db,'owner','grant','run',100);sqlite.prepare("INSERT INTO records VALUES ('trigger','owner','session','q','q','chat:v1:pending:explore','本人','2026-10-07T00:00:00Z')").run();const insert=(id)=>sqlite.prepare(CHAT_APPEND_SQL).run(id,'owner','title','body','source','expert','2026-10-07T00:01:00Z','owner','grant','run','trigger','owner');assert.equal(insert('answer1').changes,1);sqlite.prepare("INSERT INTO records VALUES ('newer','owner','session','q','q','chat:v1:pending:explore','本人','2026-10-07T00:02:00Z')").run();assert.equal(insert('answer2').changes,0);await stopRun(db,'owner','grant');assert.equal(insert('answer3').changes,0);});
