'use client';
import {useState,useEffect,useLayoutEffect,useCallback,useRef} from 'react';
import {DiscussionContext} from '@/components/discussion-context';
import {MessageBody} from '@/components/message-body';
import {type MessageReference} from '@/lib/message-presentation.mjs';
import Link from 'next/link';
import {ExperimentPanel} from '@/components/experiment-panel';
import {RoleProfile} from '@/components/role-profile';
import {type RoleId} from '@/lib/role-config';
import {Button} from '@/components/ui/button';
import {Textarea} from '@/components/ui/textarea';
import {type Entry,type RecordInput,recordInput,inputSchema,labels} from '@/lib/records';
import {MessagesSquare,Send,PanelRight,BookOpen,ChevronDown,Compass,RefreshCw,X,Square,ShieldCheck,MessageCircle,Layers3,ChevronRight,FlaskConical} from 'lucide-react';
const members=[{id:'research',short:'研',name:'需求与资讯研究员',color:'blue',focus:'消息源 · 用户问题 · 替代解释'},{id:'product',short:'产',name:'产品负责人',color:'violet',focus:'发散方向 · 体验 · 产品取舍'},{id:'architecture',short:'架',name:'AI / 架构专家',color:'orange',focus:'新能力 · 架构 · 实验'},{id:'growth',short:'编',name:'增长编辑',color:'pink',focus:'真实成果 · 表达 · 个人 IP'},{id:'skeptic',short:'疑',name:'商业质疑者',color:'green',focus:'反例 · 机会成本 · 停止条件'}];
const demo=[{role:'本人',text:'最近 AI 新东西太多了。我不想一直追工具，怎么从这些变化里，找到值得自己深入探索的问题？'},
{role:'需求与资讯研究员',text:'我想先拆开两个问题：什么值得关注，和什么值得你亲手验证。先不要急着选产品。你最近看到哪一条变化，真的改变了你对“现在能做什么”的判断？'},
{role:'AI / 架构专家',reply:'回应 需求与资讯研究员',text:'我同意先找变化，但不一定从新闻开始。你已有的语音和桌面角色探索也是线索。可以反过来问：过去体验不成立的地方，有没有因为新能力而突然可行？这需要一次小测试。'},
{role:'产品负责人',reply:'追问 AI / 架构专家',text:'“可行”还不等于值得做。我想保留两个方向一起聊：一个是表达更自然的语音体验；另一个是帮自己消化资讯。哪一个你每天真的愿意打开？'},
{role:'商业质疑者',reply:'不同意现在选方向',text:'还不用二选一。我们甚至不清楚“每天愿意打开”是因为有用还是新鲜。先找出一次具体使用场景，再谈投入上限。'},
{role:'增长编辑',text:'还有第三个角度：把这个探索过程本身变成可积累的作品。不是马上发帖，而是留下“原判断 → 实验 → 改变了什么”，以后表达就有真实材料。'}];
type Intent='explore'|'interrupt'|'summarize';
export default function Home(){const [records,setRecords]=useState<Entry[]>([]),[loaded,setLoaded]=useState(false),[error,setError]=useState(''),[sending,setSending]=useState(false),[text,setText]=useState(''),[showDemo,setShowDemo]=useState(false),[details,setDetails]=useState(false),[sideTab,setSideTab]=useState('notes'),[intent,setIntent]=useState<Intent>('explore'),[saved,setSaved]=useState(false),[activeRole,setActiveRole]=useState<RoleId|null>(null),[profileTab,setProfileTab]=useState("identity"),[experimentOpen,setExperimentOpen]=useState(false);const bottom=useRef<HTMLDivElement>(null);const pendingId=useRef<string|null>(null);const activeRun=useRef<AbortController|null>(null);const runVersion=useRef(0);const [runStatus,setRunStatus]=useState('');const [running,setRunning]=useState(false);const streamRef=useRef<HTMLDivElement>(null);const followLatest=useRef(true);const [atBottom,setAtBottom]=useState(true);
const read=useCallback(async()=>{try{const r=await fetch('/api/workspace');const v=await r.json() as {records?:Entry[],error?:string};if(!r.ok)throw new Error(v.error||'读取失败');if(!Array.isArray(v.records))throw new Error('记录暂时无法读取，请重试');setRecords(v.records);}catch(e){setError(e instanceof Error?e.message:'读取失败')}finally{setLoaded(true)}},[]);
const append=useCallback(async(data:RecordInput)=>{const v=recordInput.parse(data);const r=await fetch('/api/workspace',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(v)});const result=await r.json() as {records?:Entry[],error?:string};if(!r.ok||!Array.isArray(result.records))throw new Error(result.error||'保存失败');setRecords(result.records);setShowDemo(false);return {savedId:v.id}},[]);
useEffect(()=>{read();return()=>{if(activeRun.current){activeRun.current.abort();void fetch('/api/chat-run?action=stop',{method:'POST',keepalive:true});}}},[read]);
useEffect(()=>{const life=new AbortController();try{const mc=(document as any).modelContext;if(!mc?.registerTool)return;Promise.all([mc.registerTool({name:'read_decision_workspace',description:'Read the signed-in user’s persistent group conversation and supporting records.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute:async()=>{const r=await fetch('/api/workspace');if(!r.ok)throw new Error('读取失败');return r.json()}},{signal:life.signal}),mc.registerTool({name:'append_decision_record',description:'Append an authorized actual expert contribution or supporting record; never fabricate execution. Does not invoke AI or publish.',inputSchema,annotations:{readOnlyHint:false,untrustedContentHint:true},execute:append},{signal:life.signal})]).catch(()=>{});return()=>life.abort()}catch{life.abort()}},[append]);
const chat=records.filter(r=>['session','expert','objection','constraint','feedback'].includes(r.kind)).slice().reverse();const supporting=records.filter(r=>['evidence','decision','task'].includes(r.kind));const isDemo=showDemo||(!chat.length&&!saved);const count=chat.length;
useLayoutEffect(()=>{const el=streamRef.current;if(el&&followLatest.current)el.scrollTop=el.scrollHeight;},[records,runStatus,isDemo]);
useEffect(()=>{const el=streamRef.current;if(!el)return;const observer=new ResizeObserver(()=>{if(followLatest.current)el.scrollTop=el.scrollHeight;});observer.observe(el);return()=>observer.disconnect();},[]);
function jumpLatest(){followLatest.current=true;setAtBottom(true);const el=streamRef.current;if(el)el.scrollTop=el.scrollHeight;}

async function stop(){runVersion.current++;activeRun.current?.abort();activeRun.current=null;setRunning(false);setRunStatus('已停止；已完成的发言保留。已提交的调用可能仍计入用量');await fetch('/api/chat-run?action=stop',{method:'POST'}).catch(()=>{});}
async function discuss(triggerId:string,action:'explore'|'summarize'){
 const version=++runVersion.current;const control=new AbortController();activeRun.current=control;setRunning(true);setRunStatus('正在启动 MiniMax…');
 try{const response=await fetch('/api/chat-run',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({triggerId,intent:action}),signal:control.signal});
 if(!response.ok){const v=await response.json() as {error?:string};throw new Error(v.error||'启动失败');}if(!response.body)throw new Error('未收到响应');
 const reader=response.body.getReader();const decoder=new TextDecoder();let buffer='';let terminal=false;while(true){const item=await reader.read();if(item.done)break;buffer+=decoder.decode(item.value,{stream:true});let index;while((index=buffer.indexOf('\n'))>=0){const line=buffer.slice(0,index);buffer=buffer.slice(index+1);if(!line.trim())continue;const event=JSON.parse(line);if(version!==runVersion.current)continue;
 if(event.type==='dispatch')setRunStatus(event.role+'正在思考…');if(event.type==='result'){setRunStatus(event.role+'已回复');await read();}
 if(event.type==='complete'){terminal=true;setRunStatus('本轮完成 · 继续发送消息即可接着聊');}if(event.type==='stopped'){terminal=true;const message=event.error==='STOPPED'?'本轮已停止':event.error==='CONTEXT_TOO_LONG'?'上下文或角色资料过长，请缩短问题或角色配置后重试':'本轮遇到错误：'+event.error+'。消息和已完成发言已保存';setRunStatus(message);if(event.error!=='STOPPED')setError(message);}
 }}if(!terminal&&!control.signal.aborted&&version===runVersion.current)throw new Error('连接中断，已完成的发言保留；可停止本轮后发送新消息');
 }catch(e){if(version===runVersion.current&&!control.signal.aborted)setError(e instanceof Error?e.message:'模型调用失败');}
 finally{if(version===runVersion.current){setRunning(false);activeRun.current=null;await read();}}
}
async function send(e?:React.FormEvent,override?:{text:string,intent:Intent}){e?.preventDefault();const message=(override?.text||text).trim();if(!message||sending)return;const action=override?.intent||intent;followLatest.current=true;setAtBottom(true);setSending(true);setError('');if(running)await stop();pendingId.current??=crypto.randomUUID();const id=pendingId.current;try{const r=await fetch('/api/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id,text:message,intent:action})});const v=await r.json() as {records?:Entry[],error?:string};if(!r.ok||!Array.isArray(v.records))throw new Error(v.error||'发送失败，文字已保留');setRecords(v.records);setText('');setIntent('explore');setSaved(true);setShowDemo(false);pendingId.current=null;if(action!=='interrupt')void discuss(id,action);else setRunStatus('已保存新方向；发送下一条消息开始新一轮')}catch(e){setError(e instanceof Error?e.message:'发送失败，文字已保留')}finally{setSending(false)}}

return <div className="app"><aside className="members"><div className="brand"><span className="logo"><MessagesSquare size={23}/></span><div><strong>共想室</strong><small>你的专家群聊</small></div></div><div className="roomSelected"><MessageCircle size={18}/><span>自由讨论</span><span className="roomCount">6</span></div><div className="listLabel">群成员 <span>点击查看职责与技能</span></div>{members.map(m=><button type="button" className="member memberButton" key={m.id} onClick={()=>{setProfileTab("identity");setActiveRole(m.id as RoleId)}} aria-label={"查看"+m.name+"的职责与技能"}><span className={'avatar '+m.color}>{m.short}</span><div><strong>{m.name}</strong><small>{m.focus}</small></div></button>)}<div className="member you"><span className="avatar user">你</span><div><strong>你</strong><small>随时追问、打断、改变方向</small></div></div><div className="membersBottom"><span><Compass size={16}/>发散优先</span><p>不急着达成共识。<br/>想收敛时，由你开口。</p><div className="privacy"><ShieldCheck size={14}/>私人群聊</div></div></aside>
<main className="conversation"><header className="chatHeader"><div><h1>自由讨论 <ChevronDown size={17}/></h1><p><span className="mobileAvatars">{members.map(m=><button type="button" key={m.id} title={'查看'+m.name+'的职责与技能'} onClick={()=>{setProfileTab("identity");setActiveRole(m.id as RoleId)}} className={'tinyAvatar '+m.color}>{m.short}<small>{m.id==='research'?'研究':m.id==='product'?'产品':m.id==='architecture'?'架构':m.id==='growth'?'编辑':'质疑'}</small></button>)}</span><span>研究 · 产品 · 架构 · 表达 · 质疑</span></p></div><div className="headerActions"><Button variant="outline" className="experimentLaunch" aria-label="打开协作实验" onClick={()=>setExperimentOpen(true)}><FlaskConical size={17}/><span>协作实验</span></Button><Button variant="ghost" onClick={()=>{read()}} aria-label="刷新群聊"><RefreshCw size={17}/></Button><Button variant="outline" className={details?'active':''} onClick={()=>setDetails(!details)}><PanelRight size={17}/><span>群资料</span></Button></div></header>
<div className="modelNotice"><span className="connectionBadge">MiniMax 已连接</span><p>发送会将问题、最近对话和已采用的角色资料交给国内 MiniMax。每次研究、架构、质疑三位接话；另两位档案保留，收敛时由产品角色回复。可随时停止，不后台循环。<Link href="/trial">查看真实试跑与局限</Link></p></div>
{error&&<div className="error" role="alert"><span>{error}</span>{error.includes('登录')?<a href="/signin-with-chatgpt?return_to=%2F" target="_top">使用 ChatGPT 登录</a>:<Button variant="ghost" onClick={read}>重试读取</Button>}</div>}
<div className="stream" ref={streamRef} onScroll={e=>{const el=e.currentTarget;const near=el.scrollHeight-el.scrollTop-el.clientHeight<80;followLatest.current=near;setAtBottom(near);}} aria-label="群聊消息" aria-live="polite"><div className="streamIntro"><span className="line"/><span>{isDemo?'交互示例 · 非真实专家运行':'私人对话 · 已保存'} </span><span className="line"/></div>
{isDemo&&<div className="demoNote"><span>看看大家怎样接话、追问和提出不同意见</span>{count>0&&<Button variant="ghost" onClick={()=>setShowDemo(false)}>返回我的对话</Button>}</div>}
{isDemo?demo.map((m,i)=><ChatMessage key={'demo'+i} role={m.role} text={m.text} reply={m.reply} example/>):chat.map(m=><ChatMessage key={m.id} id={m.id} records={records} role={m.role} text={m.body} date={m.created_at} pending={m.source.startsWith('chat:v1:pending')} source={m.source.startsWith('chat:')?'':m.source}/>)}
{!isDemo&&chat.length>0&&<div className="waiting"><span className="waitingIcon"><MessagesSquare size={19}/></span><div><strong>{runStatus||'发送新消息开始一轮真实讨论'}</strong><p>角色提示不代表专家资质。没有联网搜索；事实、推断与实验建议需区分。</p></div></div>}<div ref={bottom}/></div>{!atBottom&&!isDemo&&<Button variant="outline" className="jumpLatest" onClick={jumpLatest} aria-label="回到最新消息">回到最新<ChevronDown size={14}/></Button>}
<div className="composerWrap"><div className="chatTools" aria-label="虚构场景入口"><span>试聊场景（虚构）</span>{[{name:"架构取舍",text:"虚构场景：我独自开发一个最多20人使用的知识库，预算每月50元，需要简单问答。请讨论先用关键词搜索还是向量检索，区分事实、假设、可否证实验。"},{name:"岗位与学习",text:"虚构场景：我收集了10条招聘广告，其中6条提到Python、3条提到SQL；来源和去重未核实。我每周可学习4小时。请评估能否据此选学习方向，指出证据缺口，提出低成本验证。"},{name:"海底场景教学",text:"虚构场景：我想给零基础观众展示诡异辽阔的海底世界，当前只有一个小珊瑚近景，观众说像鱼缸。我只有两天修改。请讨论空间设计、镜头与教学取舍，提出验证办法，不把审美假设当事实。"}].map(scene=><Button key={scene.name} type="button" variant="ghost" onClick={()=>{setText(scene.text);setIntent('explore');pendingId.current=null}}>{scene.name}</Button>)}</div><div className="chatTools"><Button variant="ghost" onClick={()=>{setShowDemo(!isDemo)}} disabled={!count&&isDemo}><BookOpen size={15}/>{isDemo?'返回对话':'看交互示例'}</Button><span className="toolsSpacer"/><Button variant="ghost" onClick={stop}><Square size={13}/>{running?'停止本轮':'停止后台中的本轮'}</Button><Button variant="ghost" onClick={()=>{setIntent(intent==='interrupt'?'explore':'interrupt')}} className={intent==='interrupt'?'intentSelected':''}><Square size={13}/>打断 / 换个方向</Button><Button variant="ghost" onClick={()=>{setIntent(intent==='summarize'?'explore':'summarize')}} className={intent==='summarize'?'intentSelected':''}><Layers3 size={15}/>请大家收敛</Button></div>
<form className={'composer '+(intent!=='explore'?'withIntent':'')} onSubmit={send}>{intent!=='explore'&&<div className="intentChip">{intent==='interrupt'?'打断并更新方向':'由我发起收敛'}<button type="button" aria-label="取消模式" onClick={()=>setIntent('explore')}><X size={13}/></button></div>}<Textarea aria-label="发给群里的消息" placeholder={intent==='interrupt'?'先停一下，我想换个角度……':intent==='summarize'?'请整理目前的分歧、证据和可选下一步……':'抛出一个问题，或者直接接着某位专家的话聊……'} value={text} maxLength={16000} onChange={e=>{setText(e.target.value);pendingId.current=null}} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey&&!e.nativeEvent.isComposing){e.preventDefault();send()}}}/><div className="composerFooter"><span>{intent==='explore'?'自由发散 · 你决定何时收敛':intent==='interrupt'?'你的新方向优先':'只在你要求时整理结论'}</span><Button type="submit" disabled={!text.trim()||sending||!loaded} aria-label="发送消息">{sending?'保存中':'发送给 MiniMax'}<Send size={16}/></Button></div></form><div className="composerHint">Enter 发送，Shift + Enter 换行 <span>消息持久保存 · 不自动公开发布</span></div></div></main>
<aside className={'details '+(details?'opened':'')}><div className="detailsHeader"><h2>群资料</h2><Button variant="ghost" aria-label="关闭群资料" onClick={()=>setDetails(false)}><X size={18}/></Button></div><div className="detailTabs"><Button variant="ghost" className={sideTab==='notes'?'selected':''} onClick={()=>setSideTab('notes')}>沉淀</Button><Button variant="ghost" className={sideTab==='rules'?'selected':''} onClick={()=>setSideTab('rules')}>讨论方式</Button></div>{sideTab==='notes'?<><div className="sideSection"><span className="sideIcon"><BookOpen size={20}/></span><h3>聊的过程，逐渐留下东西</h3><p>证据、判断变化和决定在这里沉淀。它们是对话的产物，不是开始聊天的门槛。</p></div>{supporting.length?supporting.map(r=><article className="note" key={r.id}><span>{labels[r.kind]}</span><h3>{r.title}</h3><p>{r.body}</p></article>):<div className="emptyNotes"><div><span>原始证据</span><span>0</span></div><div><span>判断变化</span><span>0</span></div><div><span>已确认决定</span><span>0</span></div><p>尚未形成记录。不需要为了填满这里而过早下结论。</p></div>}<div className="sideSection asset"><h3>已有探索</h3><p>语音、桌面角色、情绪 MV、AI 资讯。都可以成为讨论入口，当前实现状态尚未核实。</p></div></>:<div className="rules"><h3>意见可以不一致</h3><p>专家根据共同上下文接话，可以追问、质疑、补充新角度。不同角色的判断不等于独立验证。</p><h3>你随时插话</h3><p>新问题和新约束优先。调度者只安排发言、管理状态与调用上限，不裁定正确答案。</p><h3>只有你要求，才收敛</h3><p>自由讨论是默认状态。“请大家收敛”只改变这条消息的意图，不自动替你做决定。</p><h3>真实能力边界</h3><p>国内 MiniMax 已完成5次非敏感虚构场景测试，真实调用约3.5–5.1秒。角色会回应并质疑前面的观点，但实验阈值仍缺依据；本轮单角色2次、多角色3次，不能据此判定谁更优。每次由你发送消息启动一轮研究、架构和质疑；点收敛时由产品角色整理。可以停止或插话，未完成的旧回复不进入群聊。没有后台自循环或自动搜索、发布。</p></div>}</aside>{activeRole&&<RoleProfile key={activeRole} initialTab={profileTab} role={activeRole} onClose={()=>setActiveRole(null)}/>} {experimentOpen&&<ExperimentPanel onClose={()=>setExperimentOpen(false)} onOpenImprovements={()=>{setExperimentOpen(false);setProfileTab("changes");setActiveRole("research")}}/>}</div>}
function ChatMessage({id,records=[],role,text,reply,example,date,pending,source}:{id?:string;records?:MessageReference[];role:string;text:string;reply?:string;example?:boolean;date?:string;pending?:boolean;source?:string}){const mine=role==='本人';const member=members.find(m=>m.name===role||role.includes(m.name.split('与')[0]))||members.find(m=>role.includes('研究')&&m.id==='research');return <article id={id?'message-'+id:undefined} className={'message '+(mine?'mine':'')}><span className={'avatar '+(mine?'user':member?.color||'blue')}>{mine?'你':member?.short||'析'}</span><div className="messageContent"><div className="messageHeading"><strong>{mine?'你':role}</strong>{example?<span>示例</span>:date&&<time dateTime={date}>{new Date(date).toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit'})}</time>}</div><div className="bubble">{reply&&<div className="reply"><ChevronRight size={13}/>{reply}</div>}<MessageBody text={text} records={records} mine={mine}/></div>{pending&&<span className="messageStatus">用户消息已保存</span>}{source&&<DiscussionContext source={source} records={records}/>}</div></article>}
