'use client';
import {useEffect,useState,useRef} from 'react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Button} from '@/components/ui/button';import {Textarea} from '@/components/ui/textarea';
import {X,Pencil,BookOpen,ShieldCheck,History,Check,FlaskConical} from 'lucide-react';
import {baseline,roleNames,fieldLabels,type RoleConfig,type RoleId,type RoleState} from '@/lib/role-config';
export function RoleProfile({role,onClose,initialTab="identity"}:{role:RoleId;onClose:()=>void;initialTab?:string}){const [data,setData]=useState<RoleState>({role,version:0,approved:baseline(role),verification:'unverified',providerConnected:false,versions:[],proposals:[]}),[tab,setTab]=useState(initialTab),[editing,setEditing]=useState(false),[draft,setDraft]=useState<RoleConfig>(baseline(role)),[reason,setReason]=useState(''),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');const draftId=useRef<string|null>(null);
useEffect(()=>{let alive=true;setLoading(true);fetch('/api/roles?role='+role).then(async r=>{const v=await r.json() as RoleState&{error?:string};if(!r.ok)throw new Error(v.error||'读取失败');if(alive){setData(v);setDraft(v.approved)}}).catch(e=>{if(alive)setError(e.message)}).finally(()=>{if(alive)setLoading(false)});return()=>{alive=false}},[role]);
async function act(payload:unknown){setBusy(true);setError('');setNotice('');try{const r=await fetch('/api/roles',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const v=await r.json() as RoleState&{error?:string};if(!r.ok)throw new Error(v.error||'保存失败，编辑仍保留');setData(v);return true}catch(e){setError(e instanceof Error?e.message:'操作失败，编辑仍保留');return false}finally{setBusy(false)}}
async function propose(e:React.FormEvent){e.preventDefault();draftId.current??=crypto.randomUUID();if(await act({action:'propose',proposal:{id:draftId.current,role,baseVersion:data.version,config:draft,reason}})){setEditing(false);setTab('changes');setNotice('草案已保存，当前已批准配置没有改变。');draftId.current=null;setReason('')}}
async function review(id:string,action:'accept'|'reject'){if(await act({action,id}))setNotice(action==='accept'?'已记录你的采用确认，并保存为新版本。能力状态仍为未验证。':'已记录暂不采用，草案留在历史中。')}
return <Dialog open onOpenChange={open=>{if(!open)onClose()}}><DialogContent className="profileDrawer" showCloseButton={false} aria-describedby="profile-description"><header className="profileHead"><div><span className="profileEyebrow">成员能力档案</span><DialogTitle id="profile-title">{roleNames[role]}</DialogTitle><DialogDescription id="profile-description">{data.version===0?'设计基线 v0':'已批准配置 v'+data.version} · 不等于已验证专业能力</DialogDescription></div><Button variant="ghost" aria-label="关闭成员资料" onClick={onClose}><X size={20}/></Button></header><div className="profileStatus"><span>{data.providerConnected?'MiniMax 文本已配置':'模型未配置'}</span><span>工具未连接</span><span>已验证能力 0</span></div><div className="profileTabs">{[['identity','职责与边界',ShieldCheck],['skills','技能与评测',FlaskConical],['changes','改进与版本',History]].map(([id,label,Icon]:any)=><Button key={id} variant="ghost" className={tab===id?'selected':''} onClick={()=>{setTab(id);setEditing(false)}}><Icon size={15}/>{label}</Button>)}</div><div className="profileBody">{error&&<div className="profileError" role="alert">{error}{error.includes('登录')&&<a href="/signin-with-chatgpt?return_to=%2F" target="_top">使用 ChatGPT 登录</a>}</div>}{notice&&<div className="profileNotice" role="status"><Check size={15}/>{notice}</div>}
{editing?<form className="profileEditor" onSubmit={propose}><div className="sectionHeading"><h3>提出配置改进</h3><Button variant="ghost" type="button" onClick={()=>setEditing(false)}>取消编辑</Button></div><p className="profileMuted">基于 v{data.version} 保存草案。只有你在差异预览中明确采用后，才成为新配置。</p>{(Object.keys(fieldLabels) as (keyof RoleConfig)[]).map(field=><label key={field}>{fieldLabels[field]}<Textarea required={field==='responsibilities'||field==='constraints'} value={draft[field]} maxLength={field==='procedure'||field==='evaluation'?8000:field==='references'?6000:field==='tools'?3000:field==='lessons'?5000:4000} onChange={e=>{setDraft({...draft,[field]:e.target.value});draftId.current=null}}/></label>)}<label>为什么要改？依据来自哪里？<Textarea required maxLength={3000} value={reason} onChange={e=>{setReason(e.target.value);draftId.current=null}} placeholder="关联实际失败、评测记录或你明确提出的偏好。不要把聊天次数当作能力进步。"/></label><Button type="submit" disabled={busy||loading}>{busy?'保存中…':'保存为待审核草案'}</Button></form>:<>
{tab==='identity'&&<><div className="profileCallout"><BookOpen size={20}/><div><strong>身份设定，是协作约定</strong><p>职责和提示词能约束发言，却不能证明有专业能力。领域资料、操作步骤和评测证据需要单独积累。</p></div></div><ConfigSection label="职责" value={data.approved.responsibilities}/><ConfigSection label="边界与禁止事项" value={data.approved.constraints}/><div className="capabilityFacts"><h3>实际能力状态</h3><div><span>经过验证的技能</span><strong>暂无</strong></div><div><span>真实评测通过记录</span><strong>0</strong></div><div><span>在线检索 / 模型执行</span><strong>{data.providerConnected?'文本可用 / 检索未接通':'未接通'}</strong></div></div><Button variant="outline" onClick={()=>{setDraft(data.approved);setEditing(true)}}><Pencil size={15}/>提出修改</Button></>}
{tab==='skills'&&<><div className="skillTitle"><span className="unverified">未验证 · 设计草案</span><h3>{role==='research'?'需求证据审阅':'尚未建立专用技能'}</h3><p>批准一份配置不会自动改变验证状态。</p></div>{(['references','procedure','tools','evaluation','lessons'] as (keyof RoleConfig)[]).map(field=><ConfigSection key={field} label={fieldLabels[field]} value={data.approved[field]}/>)}<Button variant="outline" onClick={()=>{setDraft(data.approved);setEditing(true)}}><Pencil size={15}/>补充技能改进草案</Button></>}
{tab==='changes'&&<><div className="profileCallout"><History size={20}/><div><strong>记录不等于自动学习</strong><p>讨论不会训练模型权重，也不会自动修改专家。改进先成为草案，由你查看差异并明确采用，版本才改变。</p></div></div><div className="sectionHeading"><h3>待审核草案</h3><Button variant="outline" onClick={()=>{setDraft(data.approved);setEditing(true)}}><Pencil size={14}/>新建草案</Button></div>{data.proposals.filter(p=>p.status==='pending').length?data.proposals.filter(p=>p.status==='pending').map(p=><div className="proposalCard" key={p.id}><div className="proposalMeta">基于 v{p.base_version} · {new Date(p.created_at).toLocaleString('zh-CN')}</div><h4>变更依据</h4><p>{p.reason}</p>{(Object.keys(fieldLabels) as (keyof RoleConfig)[]).filter(f=>p.config[f]!==((data.versions.find(v=>v.version===p.base_version)?.config||baseline(role))[f])).map(f=><details className="diff" key={f} open={f==='responsibilities'||f==='constraints'}><summary>{fieldLabels[f]}</summary><div><section><span>原内容</span><p>{(data.versions.find(v=>v.version===p.base_version)?.config||baseline(role))[f]||'空'}</p></section><section><span>拟修改为</span><p>{p.config[f]||'空'}</p></section></div></details>)}<div className="proposalActions"><Button disabled={busy||p.base_version!==data.version} onClick={()=>review(p.id,'accept')}>确认采用为 v{p.base_version+1}</Button><Button variant="outline" disabled={busy} onClick={()=>review(p.id,'reject')}>暂不采用</Button></div>{p.base_version!==data.version&&<p className="profileMuted">当前版本已变化；保留此草案，请基于最新版本重新提交。</p>}</div>):<p className="profileEmpty">目前没有待审核草案。不会从聊天中自动修改配置。</p>}<h3 className="versionHeading">版本历史</h3>{data.versions.map(v=><details className="version" key={v.version}><summary>v{v.version} · 用户明确采用 <time>{new Date(v.created_at).toLocaleString('zh-CN')}</time></summary>{(Object.keys(fieldLabels) as (keyof RoleConfig)[]).map(f=><ConfigSection key={f} label={fieldLabels[f]} value={v.config[f]}/>)}<small>草案编号：{v.proposal_id}</small></details>)}<details className="version"><summary>v0 · 初始设计基线 · 未验证</summary><p>固定基线保留。后续批准版本逐条追加，不覆盖历史。</p></details>{data.proposals.filter(p=>p.status!=='pending').length>0&&<details className="version"><summary>已审核草案</summary>{data.proposals.filter(p=>p.status!=='pending').map(p=><p key={p.id}>{p.status==='accepted'?'已采用':'暂不采用'} · {p.reason}<br/><small>{p.id}</small></p>)}</details>}</>}
</>}</div></DialogContent></Dialog>}
function ConfigSection({label,value}:{label:string;value:string}){return <section className="configSection"><h3>{label}</h3><p>{value||'尚未补充'}</p></section>}
