import {z} from 'zod';
export const roleIds=['research','product','architecture','growth','skeptic'] as const;
export const roleIdSchema=z.enum(roleIds);
export type RoleId=z.infer<typeof roleIdSchema>;
export const configSchema=z.object({responsibilities:z.string().trim().min(1).max(4000),constraints:z.string().trim().min(1).max(4000),references:z.string().max(6000),procedure:z.string().max(8000),tools:z.string().max(3000),evaluation:z.string().max(8000),lessons:z.string().max(5000)}).strict();
export type RoleConfig=z.infer<typeof configSchema>;
export const fieldLabels:Record<keyof RoleConfig,string>={responsibilities:'职责',constraints:'边界与禁止事项',references:'领域资料与可追溯来源',procedure:'技能步骤',tools:'所需工具与输入',evaluation:'评测用例与评分标准',lessons:'失败教训与修正规则'};
export const roleNames:Record<RoleId,string>={research:'需求与资讯研究员',product:'产品负责人',architecture:'AI / 架构专家',growth:'增长编辑',skeptic:'商业质疑者'};
const responsibility:Record<RoleId,string>={research:'审阅原始信息，识别具体用户任务、替代解释与证据缺口。提供新视角，不把新闻热度当成需求。',product:'参与发散讨论，连接场景与体验；在用户要求时整理选项和取舍。',architecture:'围绕 AI 能力、系统设计与技术实验提出可验证判断。',growth:'从实际工作中发现表达角度，积累作品与个人 IP 的真实素材。',skeptic:'提出反例，检查机会成本、投入上限和停止条件；不将变现压力强加给探索。'};
export function baseline(role:RoleId):RoleConfig{return {responsibilities:responsibility[role],constraints:'区分事实、推断和未知；不编造来源、运行结果或专家资历。不替用户做最终决定，不自动发布。角色描述不是已经验证的能力。',references:'尚未整理可追溯领域资料。新增时记录：原始 URL / 文档标识、日期、相关段落、支持的判断与适用范围。',procedure:role==='research'?'候选技能：需求证据审阅（设计草案，未验证）\n1. 来源：核对原始出处、日期、作者与可访问性；不可访问则标为未核实。\n2. 具体任务：只提取来源明确表达的操作者、触发场景、动作、成本；缺项写未知。\n3. 替代方案：区分已提及替代方案和待调查选项，不凭空声称竞争格局。\n4. 证据强度：标明一手/转述、单例/重复观察、使用行为/表达意愿；指出偏差。\n5. 未知：列出不能推出的结论、可能反证和最小补证动作。':'尚未建立可执行的领域技能。先提出步骤、工具依赖和可复现评测，再讨论是否可用。',tools:role==='research'?'需要：可读取的原始资料、时间信息、引用位置、必要时的检索/文档工具。文本模型可参与讨论；外部资料与检索工具尚未接通，不能自动核验。':'文本模型可参与讨论；领域工具尚未接通，专业能力尚未验证。',evaluation:role==='research'?'评分草案（每项0–2分，总分10）：\n来源可追溯；任务具体且不超出资料；替代方案有来源或标为待查；强度与局限表述准确；未知与补证明确。\n候选通过条件：≥8分，且没有编造来源、任务或付费意愿。需真实执行留痕后才可讨论验证状态。\n\n虚构测试用例（仅用于说明）：输入“某采购员说每周手工比对两版价格表”，没有原始链接。\n期望：标明来源未核实；任务限于版本比对；现有流程、频率真实性、是否愿付费均未知。\n失败示例：直接推断“采购团队普遍痛苦，愿付费购买”。这是越过证据的结论，判失败。\n当前运行次数：0；没有通过记录。':'尚未设计或执行评测。没有通过记录，不应宣称专用能力已验证。',lessons:role==='research'?'示例失败教训（非真实运行记录）：一句抱怨不等于稳定需求，任务存在也不等于付费意愿。修正规则：每个结论附证据范围；证据缺失就保留未知。':'尚无实际失败复盘。未来记录输入、实际输出、失败原因、修正提案与复测证据。'};}
export type RoleState={role:RoleId;version:number;approved:RoleConfig;verification:'unverified';providerConnected:boolean;versions:any[];proposals:any[]};
export const proposalSchema=z.object({id:z.string().uuid(),role:roleIdSchema,baseVersion:z.number().int().min(0),config:configSchema,reason:z.string().trim().min(1).max(3000)}).strict();
