import {env} from 'cloudflare:workers';
import {baseline,proposalSchema,type RoleId} from './role-config';
function db(){if(!env.DB)throw new Error('Storage unavailable');return env.DB;}
export async function getRole(owner:string,role:RoleId){const versions=await db().prepare('SELECT version,config_json,proposal_id,created_at FROM role_versions WHERE owner=? AND role=? ORDER BY version DESC').bind(owner,role).all<any>();const proposals=await db().prepare('SELECT id,base_version,config_json,reason,status,created_at,reviewed_at FROM role_proposals WHERE owner=? AND role=? ORDER BY created_at DESC').bind(owner,role).all<any>();const parsed=versions.results.map(r=>({...r,config:JSON.parse(r.config_json),config_json:undefined}));return {role,version:parsed[0]?.version||0,approved:parsed[0]?.config||baseline(role),verification:'unverified',providerConnected:!!(env as unknown as Record<string,unknown>).MINIMAX_API_KEY,versions:parsed,proposals:proposals.results.map(r=>({...r,config:JSON.parse(r.config_json),config_json:undefined}))};}
export async function proposeRole(owner:string,input:unknown){const v=proposalSchema.parse(input);const existing=await db().prepare('SELECT owner FROM role_proposals WHERE id=?').bind(v.id).first<{owner:string}>();if(existing&&existing.owner!==owner)throw new Error('CONFLICT');await db().prepare('INSERT INTO role_proposals (id,owner,role,base_version,config_json,reason,status,created_at) VALUES (?,?,?,?,?,?,?,?) ON CONFLICT(id) DO NOTHING').bind(v.id,owner,v.role,v.baseVersion,JSON.stringify(v.config),v.reason,'pending',new Date().toISOString()).run();return getRole(owner,v.role);}
export async function reviewRole(owner:string,id:string,action:'accept'|'reject'){const proposal=await db().prepare('SELECT role,status FROM role_proposals WHERE id=? AND owner=?').bind(id,owner).first<{role:RoleId,status:string}>();if(!proposal)throw new Error('NOT_FOUND');const now=new Date().toISOString();if(action==='reject'){if(proposal.status==='accepted')throw new Error('CONFLICT');await db().prepare("UPDATE role_proposals SET status='rejected',reviewed_at=? WHERE id=? AND owner=? AND status='pending'").bind(now,id,owner).run();}else if(proposal.status==='pending'){await db().batch([
 db().prepare("INSERT OR IGNORE INTO role_versions (id,owner,role,version,config_json,proposal_id,created_at) SELECT ?,p.owner,p.role,p.base_version+1,p.config_json,p.id,? FROM role_proposals p WHERE p.id=? AND p.owner=? AND p.status='pending' AND p.base_version=(SELECT COALESCE(MAX(v.version),0) FROM role_versions v WHERE v.owner=p.owner AND v.role=p.role)").bind(crypto.randomUUID(),now,id,owner),
 db().prepare("UPDATE role_proposals SET status='accepted',reviewed_at=? WHERE id=? AND owner=? AND EXISTS (SELECT 1 FROM role_versions v WHERE v.proposal_id=role_proposals.id)").bind(now,id,owner)
 ]);const after=await db().prepare('SELECT status FROM role_proposals WHERE id=? AND owner=?').bind(id,owner).first<{status:string}>();if(after?.status!=='accepted')throw new Error('STALE_VERSION');}else if(proposal.status!=='accepted')throw new Error('CONFLICT');return getRole(owner,proposal.role);}
