import { sqliteTable, text, index, integer, uniqueIndex } from 'drizzle-orm/sqlite-core';
export const records=sqliteTable('records',{id:text('id').primaryKey(),owner:text('owner').notNull(),kind:text('kind').notNull(),title:text('title').notNull(),body:text('body').notNull(),source:text('source').notNull(),role:text('role').notNull(),createdAt:text('created_at').notNull()},t=>[index('idx_records_owner_created').on(t.owner,t.createdAt)]);
export const roleProposals=sqliteTable('role_proposals',{id:text('id').primaryKey(),owner:text('owner').notNull(),role:text('role').notNull(),baseVersion:integer('base_version').notNull(),configJson:text('config_json').notNull(),reason:text('reason').notNull(),status:text('status').notNull(),createdAt:text('created_at').notNull(),reviewedAt:text('reviewed_at')},t=>[index('idx_role_proposals_owner_role').on(t.owner,t.role)]);
export const roleVersions=sqliteTable('role_versions',{id:text('id').primaryKey(),owner:text('owner').notNull(),role:text('role').notNull(),version:integer('version').notNull(),configJson:text('config_json').notNull(),proposalId:text('proposal_id').notNull(),createdAt:text('created_at').notNull()},t=>[uniqueIndex('uq_role_versions_owner_role_version').on(t.owner,t.role,t.version),uniqueIndex('uq_role_versions_proposal').on(t.proposalId)]);
export const experiments=sqliteTable('experiments',{id:text('id').primaryKey(),owner:text('owner').notNull(),planJson:text('plan_json').notNull(),createdAt:text('created_at').notNull()},t=>[index('idx_experiments_owner_created').on(t.owner,t.createdAt)]);
export const experimentEntries=sqliteTable('experiment_entries',{id:text('id').primaryKey(),owner:text('owner').notNull(),experimentId:text('experiment_id').notNull(),kind:text('kind').notNull(),arm:text('arm').notNull(),payloadJson:text('payload_json').notNull(),createdAt:text('created_at').notNull()},t=>[index('idx_experiment_entries_owner_experiment').on(t.owner,t.experimentId)]);

// One finite approval per owner; replacing/resetting this requires a new explicit grant.
export const executionGrants=sqliteTable('execution_grants',{owner:text('owner').primaryKey(),grantId:text('grant_id').notNull(),expiresAt:integer('expires_at').notNull(),status:text('status').notNull(),activeRun:text('active_run'),callsUsed:integer('calls_used').notNull().default(0),inputBytesUsed:integer('input_bytes_used').notNull().default(0),outputTokensReserved:integer('output_tokens_reserved').notNull().default(0),lastCallAt:integer('last_call_at').notNull().default(0),reservationToken:text('reservation_token')});
export const executionCalls=sqliteTable('execution_calls',{id:text('id').primaryKey(),owner:text('owner').notNull(),grantId:text('grant_id').notNull(),runId:text('run_id').notNull(),arm:text('arm').notNull(),inputBytes:integer('input_bytes').notNull(),outputTokens:integer('output_tokens').notNull(),status:text('status').notNull(),createdAt:integer('created_at').notNull(),resultJson:text('result_json')},t=>[index('idx_execution_calls_owner_grant').on(t.owner,t.grantId)]);
